### ISSUE TITLE
Request file of reaxys_polymerization_filtered.csv

### ISSUE THREAD

**Issue by huangxiang701** [TheJacksonLab/OpenMacromolecularGenome#5]
A powerful repository, I would appreciate if the file of  ‘reaxys_polymerization_filtered.csv’ could be disclosed!
![1](https://github.com/user-attachments/assets/4136f562-1c71-4ca9-a602-534829431da5)

**Comment by ShKim77** [comment]
Thanks for reaching out to us! Unfortunately, we cannot open copyrighted Reaxys data. Instead, you can directly search polymerization reaction data from Reaxys (https://www.reaxys.com/). Please let us know if you have any other questions. I'll be closing this issue!
